### ISSUE TITLE
Support usage from a toml configuration

### ISSUE THREAD

**Issue by xgdgsc** [sigmaSd/Eltrafico#2]
and the same YAML format?

**Comment by sigmaSd** [comment]
Well Supporting all traffictoll options is a goal, but personally I don't think I'm going to add this for now, hopefully someone interested sends a PR.

**Comment by sigmaSd** [comment]
I updated the back-end to match traffictoll latest commit, so now the back-end knows about those recent attributes like minimum.

Whats left now is:
- [ ] plumb this through the rpc interface for example here https://github.com/sigmaSd/Eltrafico/blob/master/crates/tc/src/main.rs#L118 (we're just setting the new attributes to None)
- [ ] Update the gui with new elements that interacts with these attributes

I don't know when I can do this, if someone in the mean time wants to send a PR that would be great

Note: This update might have broke stuff, I will hopefully fix what I notice, for now it seems to work fine

**Comment by sigmaSd** [comment]
fixed in https://github.com/sigmaSd/Eltrafico/commit/5e0987b8c8063c56d75a7ef773438909cfdf5920
