### ISSUE TITLE
consider changing cli program name

### ISSUE THREAD

**Issue by xgdgsc** [sigmaSd/Eltrafico#5]
Would it be a bit strange that it has the same name as tc? Consider changing to `el` or something?

**Comment by sigmaSd** [comment]
yep that's very reasonable, I'll change it to something else.

**Comment by sigmaSd** [comment]
fixed in https://github.com/sigmaSd/Eltrafico/commit/3e0addb7b776d456989b95bd5cb380dd37c8bf8e
