### ISSUE TITLE
ipv6 ss results 

### ISSUE THREAD

**Issue by xgdgsc** [sigmaSd/Eltrafico#6]
run `ss -n -t -p  state established` could have ipv6 results like:

```
0      0                        [::1]:9100                                 [::1]:33586               users:(("node_exporter",pid=111305,fd=5))
0      0                        [::1]:33586                                [::1]:9100                users:(("sshd",pid=261247,fd=10))

```
 cause empty `con.lport`. 

Don' t know if skipping them cause issues:

https://github.com/sigmaSd/Eltrafico/commit/6acc97f070ef810c33c8dbce3f2fb188b84e37bf

**Comment by sigmaSd** [comment]
I added ip6 parsing to ss here https://github.com/sigmaSd/Eltrafico/commit/7071c868ad898d8fe2ac0720fdf88f3e2d089096

maybe that's enough?

**Comment by xgdgsc** [comment]
Thanks. Seems fine.
